server:
  port: 8965

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #通过 eureka.client.registerWithEureka=false 和 fetchRegistry=false 来表明自己是一个eureka server。
    fetchRegistry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
